apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-service-volume
  labels:
    type: local
spec:
  #kubectl get storageclass
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
