apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serving-service-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
