apiVersion: v1
kind: ConfigMap
metadata:
  name: api-celery-config
  labels:
    app: skipper-api-celery
data:
  WORKFLOW_URL: http://skipper-workflow:5000/api/v1/skipper/workflow/
  LOGGER_PRODUCER_URL: http://skipper-logger:5001/api/v1/skipper/logger/log_producer
  RABBITMQ_BROKER: pyamqp://skipper:welcome1@rabbitmq-0.rabbitmq.rabbits.svc.cluster.local//
  RABBITMQ_HOST: rabbitmq-0.rabbitmq.rabbits.svc.cluster.local
  RABBITMQ_PORT: '5672'

---

apiVersion: v1
kind: Secret
metadata:
  name: api-celery-secret
type: Opaque
data:
  RABBITMQ_USER: c2tpcHBlcg==
  RABBITMQ_PASSWORD: d2VsY29tZTE=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper-api-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skipper-api-celery
  template:
    metadata:
      labels:
        app: skipper-api-celery
    spec:
      containers:
        - image: katanaml/skipper-api:latest
          name: skipper-api-celery
          command: ["celery"]
          args: ["-A", "api.worker", "worker", "--loglevel=INFO"]
          imagePullPolicy: IfNotPresent
          env:
            - name: WORKFLOW_URL
              valueFrom:
                configMapKeyRef:
                  name: api-celery-config
                  key: WORKFLOW_URL
            - name: LOGGER_PRODUCER_URL
              valueFrom:
                configMapKeyRef:
                  name: api-celery-config
                  key: LOGGER_PRODUCER_URL
            - name: RABBITMQ_BROKER
              valueFrom:
                configMapKeyRef:
                  name: api-celery-config
                  key: RABBITMQ_BROKER
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-celery-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-celery-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: api-celery-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-celery-secret
                  key: RABBITMQ_PASSWORD
